In [1]:
'''
Author: Aditya Vivek Khatode
title: Deep Learning
'''
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline

import keras
from keras.layers import Dense, Activation,Dropout
from keras.models import Sequential

In [2]:
name= ['CRIM', 'ZN', 'INDUS', 'CHAS', 'NOX', 'RM', 'AGE', 'DIS', 'RAD', 'TAX', 'PTRATIO', 'B', 'LSTAT', 'PRICE']
df = pd.read_csv(filepath_or_buffer="housing.csv",delim_whitespace=True,names=name)
df.head()

,CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,LSTAT,PRICE
0,0.00632,18.0,2.31,0,0.538,6.575,65.2,4.0900,1,296.0,15.3,396.90,4.98,24.0
1,0.02731,0.0,7.07,0,0.469,6.421,78.9,4.9671,2,242.0,17.8,396.90,9.14,21.6
2,0.02729,0.0,7.07,0,0.469,7.185,61.1,4.9671,2,242.0,17.8,392.83,4.03,34.7
3,0.03237,0.0,2.18,0,0.458,6.998,45.8,6.0622,3,222.0,18.7,394.63,2.94,33.4
4,0.06905,0.0,2.18,0,0.458,7.147,54.2,6.0622,3,222.0,18.7,396.90,5.33,36.2

In [3]:
print(df.shape)

(506, 14)

In [4]:
df.describe()

,CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,LSTAT,PRICE
count,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000
mean,3.613524,11.363636,11.136779,0.069170,0.554695,6.284634,68.574901,3.795043,9.549407,408.237154,18.455534,356.674032,12.653063,22.532806
std,8.601545,23.322453,6.860353,0.253994,0.115878,0.702617,28.148861,2.105710,8.707259,168.537116,2.164946,91.294864,7.141062,9.197104
min,0.006320,0.000000,0.460000,0.000000,0.385000,3.561000,2.900000,1.129600,1.000000,187.000000,12.600000,0.320000,1.730000,5.000000
25%,0.082045,0.000000,5.190000,0.000000,0.449000,5.885500,45.025000,2.100175,4.000000,279.000000,17.400000,375.377500,6.950000,17.025000
50%,0.256510,0.000000,9.690000,0.000000,0.538000,6.208500,77.500000,3.207450,5.000000,330.000000,19.050000,391.440000,11.360000,21.200000
75%,3.677083,12.500000,18.100000,0.000000,0.624000,6.623500,94.075000,5.188425,24.000000,666.000000,20.200000,396.225000,16.955000,25.000000
max,88.976200,100.000000,27.740000,1.000000,0.871000,8.780000,100.000000,12.126500,24.000000,711.000000,22.000000,396.900000,37.970000,50.000000

In [6]:
# Splitting the dependent feature and independent feature
X = df.iloc[:,:-1]
y= df.PRICE

In [10]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size = 0.2, random_state = 4)

In [11]:
print(X_train.shape)
print(X_test.shape)
print(y_train.shape)
print(y_test.shape)

(404, 13)
(102, 13)
(404,)
(102,)

In [11]:
#Scaling the dataset
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [12]:
model = Sequential()

model.add(Dense(128,activation  = 'relu',input_dim =13))
model.add(Dense(64,activation  = 'relu'))
model.add(Dense(32,activation  = 'relu'))
model.add(Dense(16,activation  = 'relu'))
model.add(Dense(1))
model.compile(optimizer = 'adam',loss = 'mean_squared_error')

In [13]:
model.fit(X_train, y_train, epochs = 100)

Epoch 1/100
13/13 [==============================] - 2s 5ms/step - loss: 552.3865
Epoch 2/100
13/13 [==============================] - 0s 5ms/step - loss: 465.4070
Epoch 3/100
13/13 [==============================] - 0s 4ms/step - loss: 258.6259
Epoch 4/100
13/13 [==============================] - 0s 4ms/step - loss: 77.6297
Epoch 5/100
13/13 [==============================] - 0s 4ms/step - loss: 49.0921
Epoch 6/100
13/13 [==============================] - 0s 6ms/step - loss: 32.3260
Epoch 7/100
13/13 [==============================] - 0s 4ms/step - loss: 23.5983
Epoch 8/100
13/13 [==============================] - 0s 4ms/step - loss: 20.7758
Epoch 9/100
13/13 [==============================] - 0s 4ms/step - loss: 18.7439
Epoch 10/100
13/13 [==============================] - 0s 5ms/step - loss: 17.5775
Epoch 11/100
13/13 [==============================] - 0s 6ms/step - loss: 16.6593
Epoch 12/100
13/13 [==============================] - 0s 5ms/step - loss: 15.8755
Epoch 13/100
13/13 [==============================] - 0s 5ms/step - loss: 14.9203
Epoch 14/100
13/13 [==============================] - 0s 5ms/step - loss: 14.1476
Epoch 15/100
13/13 [==============================] - 0s 4ms/step - loss: 13.8343
Epoch 16/100
13/13 [==============================] - 0s 4ms/step - loss: 13.2050
Epoch 17/100
13/13 [==============================] - 0s 4ms/step - loss: 12.9515
Epoch 18/100
13/13 [==============================] - 0s 4ms/step - loss: 12.7549
Epoch 19/100
13/13 [==============================] - 0s 5ms/step - loss: 12.8648
Epoch 20/100
13/13 [==============================] - 0s 4ms/step - loss: 12.0392
Epoch 21/100
13/13 [==============================] - 0s 5ms/step - loss: 11.6206
Epoch 22/100
13/13 [==============================] - 0s 5ms/step - loss: 11.3270
Epoch 23/100
13/13 [==============================] - 0s 6ms/step - loss: 11.2529
Epoch 24/100
13/13 [==============================] - 0s 7ms/step - loss: 10.8332
Epoch 25/100
13/13 [==============================] - 0s 9ms/step - loss: 10.6882
Epoch 26/100
13/13 [==============================] - 0s 12ms/step - loss: 10.5629
Epoch 27/100
13/13 [==============================] - 0s 9ms/step - loss: 10.1779
Epoch 28/100
13/13 [==============================] - 0s 7ms/step - loss: 10.0978
Epoch 29/100
13/13 [==============================] - 0s 7ms/step - loss: 9.8593
Epoch 30/100
13/13 [==============================] - 0s 6ms/step - loss: 9.6131
Epoch 31/100
13/13 [==============================] - 0s 5ms/step - loss: 9.4162
Epoch 32/100
13/13 [==============================] - 0s 5ms/step - loss: 9.2860
Epoch 33/100
13/13 [==============================] - 0s 6ms/step - loss: 9.2195
Epoch 34/100
13/13 [==============================] - 0s 6ms/step - loss: 8.8826
Epoch 35/100
13/13 [==============================] - 0s 6ms/step - loss: 8.5523
Epoch 36/100
13/13 [==============================] - 0s 5ms/step - loss: 8.6972
Epoch 37/100
13/13 [==============================] - 0s 6ms/step - loss: 8.5395
Epoch 38/100
13/13 [==============================] - 0s 6ms/step - loss: 8.1580
Epoch 39/100
13/13 [==============================] - 0s 6ms/step - loss: 8.1588
Epoch 40/100
13/13 [==============================] - 0s 4ms/step - loss: 8.1949
Epoch 41/100
13/13 [==============================] - 0s 4ms/step - loss: 7.6856
Epoch 42/100
13/13 [==============================] - 0s 4ms/step - loss: 7.9507
Epoch 43/100
13/13 [==============================] - 0s 3ms/step - loss: 7.5529
Epoch 44/100
13/13 [==============================] - 0s 3ms/step - loss: 7.3080
Epoch 45/100
13/13 [==============================] - 0s 6ms/step - loss: 7.6465
Epoch 46/100
13/13 [==============================] - 0s 6ms/step - loss: 7.2451
Epoch 47/100
13/13 [==============================] - 0s 5ms/step - loss: 6.9437
Epoch 48/100
13/13 [==============================] - 0s 6ms/step - loss: 6.8097
Epoch 49/100
13/13 [==============================] - 0s 6ms/step - loss: 6.6311
Epoch 50/100
13/13 [==============================] - 0s 6ms/step - loss: 6.6402
Epoch 51/100
13/13 [==============================] - 0s 7ms/step - loss: 6.2765
Epoch 52/100
13/13 [==============================] - 0s 6ms/step - loss: 6.4365
Epoch 53/100
13/13 [==============================] - 0s 6ms/step - loss: 6.5396
Epoch 54/100
13/13 [==============================] - 0s 5ms/step - loss: 6.2311
Epoch 55/100
13/13 [==============================] - 0s 4ms/step - loss: 6.1558
Epoch 56/100
13/13 [==============================] - 0s 3ms/step - loss: 6.0871
Epoch 57/100
13/13 [==============================] - 0s 3ms/step - loss: 6.4318
Epoch 58/100
13/13 [==============================] - 0s 3ms/step - loss: 5.7692
Epoch 59/100
13/13 [==============================] - 0s 3ms/step - loss: 5.6346
Epoch 60/100
13/13 [==============================] - 0s 3ms/step - loss: 5.4328
Epoch 61/100
13/13 [==============================] - 0s 3ms/step - loss: 5.4230
Epoch 62/100
13/13 [==============================] - 0s 7ms/step - loss: 5.7041
Epoch 63/100
13/13 [==============================] - 0s 5ms/step - loss: 5.7387
Epoch 64/100
13/13 [==============================] - 0s 5ms/step - loss: 5.4602
Epoch 65/100
13/13 [==============================] - 0s 5ms/step - loss: 5.3705
Epoch 66/100
13/13 [==============================] - 0s 4ms/step - loss: 5.3451
Epoch 67/100
13/13 [==============================] - 0s 3ms/step - loss: 5.1898
Epoch 68/100
13/13 [==============================] - 0s 3ms/step - loss: 4.8151
Epoch 69/100
13/13 [==============================] - 0s 3ms/step - loss: 5.1027
Epoch 70/100
13/13 [==============================] - 0s 3ms/step - loss: 4.9391
Epoch 71/100
13/13 [==============================] - 0s 5ms/step - loss: 5.0980
Epoch 72/100
13/13 [==============================] - 0s 7ms/step - loss: 4.6901
Epoch 73/100
13/13 [==============================] - 0s 8ms/step - loss: 4.7113
Epoch 74/100
13/13 [==============================] - 0s 5ms/step - loss: 4.5177
Epoch 75/100
13/13 [==============================] - 0s 4ms/step - loss: 4.7152
Epoch 76/100
13/13 [==============================] - 0s 3ms/step - loss: 4.4681
Epoch 77/100
13/13 [==============================] - 0s 4ms/step - loss: 4.4004
Epoch 78/100
13/13 [==============================] - 0s 4ms/step - loss: 4.4748
Epoch 79/100
13/13 [==============================] - 0s 4ms/step - loss: 4.4848
Epoch 80/100
13/13 [==============================] - 0s 4ms/step - loss: 4.2427
Epoch 81/100
13/13 [==============================] - 0s 6ms/step - loss: 4.1223
Epoch 82/100
13/13 [==============================] - 0s 5ms/step - loss: 3.9933
Epoch 83/100
13/13 [==============================] - 0s 6ms/step - loss: 4.3720
Epoch 84/100
13/13 [==============================] - 0s 5ms/step - loss: 4.3300
Epoch 85/100
13/13 [==============================] - 0s 6ms/step - loss: 4.7267
Epoch 86/100
13/13 [==============================] - 0s 4ms/step - loss: 4.3556
Epoch 87/100
13/13 [==============================] - 0s 4ms/step - loss: 3.9730
Epoch 88/100
13/13 [==============================] - 0s 4ms/step - loss: 3.8936
Epoch 89/100
13/13 [==============================] - 0s 4ms/step - loss: 3.7266
Epoch 90/100
13/13 [==============================] - 0s 5ms/step - loss: 3.7359
Epoch 91/100
13/13 [==============================] - 0s 4ms/step - loss: 3.9173
Epoch 92/100
13/13 [==============================] - 0s 5ms/step - loss: 3.7294
Epoch 93/100
13/13 [==============================] - 0s 6ms/step - loss: 3.5959
Epoch 94/100
13/13 [==============================] - 0s 5ms/step - loss: 3.5731
Epoch 95/100
13/13 [==============================] - 0s 5ms/step - loss: 3.6813
Epoch 96/100
13/13 [==============================] - 0s 4ms/step - loss: 3.5065
Epoch 97/100
13/13 [==============================] - 0s 4ms/step - loss: 3.4653
Epoch 98/100
13/13 [==============================] - 0s 4ms/step - loss: 3.4578
Epoch 99/100
13/13 [==============================] - 0s 4ms/step - loss: 3.3458
Epoch 100/100
13/13 [==============================] - 0s 4ms/step - loss: 3.3814

In [16]:
new_input=np.array([[0.00632,18.0,2.31,0,0.538,6.575,65.2,4.0900,1,296.0,15.3,396.90,4.98]])
new_input=sc.transform(new_input)
prediction=model.predict(new_input)
print(prediction)

1/1 [==============================] - 0s 33ms/step
[[24.639315]]

C:\Users\Aditya\anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(